name: stretch_wrap
description: "A Flutter widget that wraps children into multiple rows and stretches designated children to fill the remaining space in each row."
version: 0.0.1
homepage: "https://github.com/abrahammurciano/stretch_wrap"

environment:
  sdk: "^3.6.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=5.0.0"
