name: Publish to pub.dev

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Set version
        run: 'sed -e "s/^version: 0.0.0$/version: $(echo ${{ github.event.release.tag_name }} | cut -d v -f 2)/" -i pubspec.yaml'
      - name: Install dependencies
        run: flutter pub get
      - name: Setup Pub Credentials
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart
          echo '${{ secrets.PUB_CREDENTIALS }}' > $XDG_CONFIG_HOME/dart/pub-credentials.json
      - name: Publish package
        run: flutter pub publish --force